"""
pages/summary_page.py

Displays the AI-generated study summary for the currently processed video.
"""

import streamlit as st

from session_utils import initialize_session_state
from ui_theme import inject_global_css, render_header, render_section_label, render_no_video_notice


st.set_page_config(
    page_title="Summary · Video Learning Assistant",
    page_icon="📄",
    layout="wide",
    initial_sidebar_state="expanded",
)


def render_sidebar_nav() -> None:
    """Render the shared sidebar navigation."""
    with st.sidebar:
        st.markdown("### 🎓 Navigation")
        st.page_link("app.py", label="Process Video", icon="🏠")
        st.page_link("pages/summary_page.py", label="Summary", icon="📄")
        st.page_link("pages/notes_page.py", label="Key Notes", icon="🗒️")
        st.page_link("pages/chat_page.py", label="Doubt Clarification", icon="💬")


import re

def render_summary_card() -> None:

    render_section_label("Video Summary")

    summary = st.session_state.summary

    with st.container(border=True):
        st.markdown(
            f"""
            <div class="ed-summary-text">
            {summary}
            </div>
            """,
            unsafe_allow_html=True
        )


def main() -> None:
    """Page entry point."""
    inject_global_css()
    initialize_session_state()
    render_sidebar_nav()

    render_header("Summary", "A study-ready overview of the video, generated by AI.")

    if not st.session_state.video_processed or not st.session_state.summary:
        render_no_video_notice("the Summary page")
        return

    render_summary_card()


if __name__ == "__main__":
    main()  